package azelha.karimerri.entites;

public class ProductModel {
	public String barcode_number;
	public String barcode_type;
	public String barcode_formats;
	public String mpn;
	public String model;
	public String asin;
	public String product_name;
	public String title;
	public String category;
	public String manufacturer;
	public String brand;
	public String label;
	public String author;
	public String publisher;
	public String artist;
	public String actor;
	public String director;
	public String studio;
	public String genre;
	public String audience_rating;
	public String ingredients;
	public String nutrition_facts;
	public String color;
	public String format;
	public String package_quantity;
	public String size;
	public String length;
	public String width;
	public String height;
	public String weight;
	public String release_date;
	public String description;
	public Object[] features;
	public String[] images;
	public Store[] stores;
	public Review[] reviews;
}