name: azelha
description: Azelha Application
authors:
  - Karim Merri <karimerri@gmail.com>

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  intro_views_flutter: ^2.8.2
  splashscreen: ^1.3.5
  geolocator: ^6.1.7
  geocoding: ^1.0.5
  google_maps_flutter: ^1.0.6
  flutter_polyline_points: ^0.2.4
  flappy_search_bar: ^1.7.2
  circle_wheel_scroll: ^0.0.1+1
  loadinglistview: ^0.0.2
  flutter_typeahead: ^1.9.1
  animated_text_kit: ^3.1.0
  rxdart: ^0.25.0
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4
  cryptoutils: ^0.4.0
  awesome_dialog: ^1.3.0
  barcode_scan: ^3.0.1
  flutter_sparkline: ^0.1.0
  flutter_credit_card: ^0.1.4
  uuid: ^2.2.2
  stripe_payment: ^1.0.9
  fluttertoast: ^7.1.6
  grouped_buttons: ^1.0.4
  sqflite: ^1.3.2+2
  typicons_flutter: ^0.4.2
  crypto_font_icons: ^0.1.0+1
  intl: ^0.16.1
  #shimmer: ^1.1.2
#  flutter_spinkit: ^4.1.2+1
 # progress_button: ^0.0.2
#  drawing_animation: ^0.1.4
  #path_provider: ^0.5.0
 # simple_permissions: ^0.1.9
# vector_math: ^2.0.8
 # fluttie: ^0.5.0
 # wave: ^0.1.0
 # liquid_pull_to_refresh: ^2.0.0
 # fancy_bottom_navigation: ^0.3.2
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
     - family: EcoRegular
       fonts:
         - asset: assets/Fonts/LatoRegular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

